number1=10
number2=11
number3=12
number4=13
add=number1+number2+number3+number4
mult=number1*number2*number3*number4
subtract=number4-number3-number2-number1
division=(number4/number3)
print(add)
print(mult)
print(subtract)
print(division)
number1=13
number2=12
number3=11
number4=10
add=number1+number2+number3+number4
mult=number1*number2*number3*number4
subtract=number4-number3-number2-number1
division=(number4/number3)
print(add)
print(mult)
print(subtract)
print(division)
add=number1+number2
mult=number3*number4
subtract=number1-number2
division=number1/number2
print(add)
print(mult)
print(subtract)
print(division)